# Generated by Django 4.0.1 on 2022-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimagetodatabase',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
